// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// colSumsSub
arma::rowvec colSumsSub(const arma::mat& mat, const arma::uvec& rowIDs);
RcppExport SEXP _dga_colSumsSub(SEXP matSEXP, SEXP rowIDsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type rowIDs(rowIDsSEXP);
    rcpp_result_gen = Rcpp::wrap(colSumsSub(mat, rowIDs));
    return rcpp_result_gen;
END_RCPP
}
// computeML
void computeML(arma::mat& inPlace, int j, const arma::mat& compMat, const arma::uvec& decC, const arma::uvec& decS, const arma::rowvec& denominator);
RcppExport SEXP _dga_computeML(SEXP inPlaceSEXP, SEXP jSEXP, SEXP compMatSEXP, SEXP decCSEXP, SEXP decSSEXP, SEXP denominatorSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type inPlace(inPlaceSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type compMat(compMatSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type decC(decCSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type decS(decSSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type denominator(denominatorSEXP);
    computeML(inPlace, j, compMat, decC, decS, denominator);
    return R_NilValue;
END_RCPP
}
// rowAdd
void rowAdd(arma::mat& mat, const arma::rowvec& v);
RcppExport SEXP _dga_rowAdd(SEXP matSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type v(vSEXP);
    rowAdd(mat, v);
    return R_NilValue;
END_RCPP
}
// colAdd
void colAdd(arma::mat& mat, const arma::colvec& v);
RcppExport SEXP _dga_colAdd(SEXP matSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type v(vSEXP);
    colAdd(mat, v);
    return R_NilValue;
END_RCPP
}
// expNormalize
void expNormalize(arma::mat& mat);
RcppExport SEXP _dga_expNormalize(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type mat(matSEXP);
    expNormalize(mat);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dga_colSumsSub", (DL_FUNC) &_dga_colSumsSub, 2},
    {"_dga_computeML", (DL_FUNC) &_dga_computeML, 6},
    {"_dga_rowAdd", (DL_FUNC) &_dga_rowAdd, 2},
    {"_dga_colAdd", (DL_FUNC) &_dga_colAdd, 2},
    {"_dga_expNormalize", (DL_FUNC) &_dga_expNormalize, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_dga(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
